/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import javax.swing.ImageIcon;

/**
 *
 * @author aleja
 */
public class book_cliente extends javax.swing.JFrame {

    /**
     * Creates new form book_cliente
     */
    public book_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bookActivities = new javax.swing.JPanel();
        carrito = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        title_carrito = new javax.swing.JLabel();
        title_tour = new javax.swing.JLabel();
        title_date = new javax.swing.JLabel();
        title_adult = new javax.swing.JLabel();
        title_child = new javax.swing.JLabel();
        title_time1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tour_name = new javax.swing.JLabel();
        tour_date = new javax.swing.JLabel();
        tour_adult = new javax.swing.JLabel();
        tour_child = new javax.swing.JLabel();
        tour_total = new javax.swing.JLabel();
        title_informacion = new javax.swing.JLabel();
        btn_efectivo = new javax.swing.JButton();
        btn_tarjeta = new javax.swing.JButton();
        btn_facturacion = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        btn_pagar = new javax.swing.JButton();
        title_nombre = new javax.swing.JLabel();
        title_apellido = new javax.swing.JLabel();
        title_rfc = new javax.swing.JLabel();
        title_email = new javax.swing.JLabel();
        title_numero = new javax.swing.JLabel();
        title_direccion = new javax.swing.JLabel();
        input_nombre = new javax.swing.JTextField();
        input_apellido = new javax.swing.JTextField();
        input_rfc = new javax.swing.JTextField();
        input_email = new javax.swing.JTextField();
        input_numero = new javax.swing.JTextField();
        input_direccion = new javax.swing.JTextField();
        separador_nombre = new javax.swing.JSeparator();
        separador_nombre1 = new javax.swing.JSeparator();
        separador_nombre2 = new javax.swing.JSeparator();
        separador_nombre3 = new javax.swing.JSeparator();
        separador_nombre4 = new javax.swing.JSeparator();
        separador_nombre5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_bookActivities.setBackground(new java.awt.Color(255, 255, 255));
        panel_bookActivities.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carrito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        carrito.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 490, 10));

        title_carrito.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        title_carrito.setForeground(new java.awt.Color(0, 123, 164));
        title_carrito.setText("Carrito");
        carrito.add(title_carrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        title_tour.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_tour.setForeground(new java.awt.Color(153, 153, 153));
        title_tour.setText("Tour: ");
        carrito.add(title_tour, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        title_date.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_date.setForeground(new java.awt.Color(153, 153, 153));
        title_date.setText("Date:");
        carrito.add(title_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        title_adult.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_adult.setForeground(new java.awt.Color(153, 153, 153));
        title_adult.setText("Adult:");
        carrito.add(title_adult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        title_child.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_child.setForeground(new java.awt.Color(153, 153, 153));
        title_child.setText("Child:");
        carrito.add(title_child, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        title_time1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_time1.setForeground(new java.awt.Color(153, 153, 153));
        title_time1.setText("Time:");
        carrito.add(title_time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("00:00 hrs");
        carrito.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 120, -1));

        tour_name.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_name.setForeground(new java.awt.Color(153, 153, 153));
        tour_name.setText("Tour Mane");
        carrito.add(tour_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 240, -1));

        tour_date.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_date.setForeground(new java.awt.Color(153, 153, 153));
        tour_date.setText("00-month-0000");
        carrito.add(tour_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 250, -1));

        tour_adult.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_adult.setForeground(new java.awt.Color(153, 153, 153));
        tour_adult.setText("00");
        carrito.add(tour_adult, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 50, -1));

        tour_child.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_child.setForeground(new java.awt.Color(153, 153, 153));
        tour_child.setText("00");
        carrito.add(tour_child, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 50, -1));

        tour_total.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        tour_total.setForeground(new java.awt.Color(0, 102, 255));
        tour_total.setText("$0000.00 USD");
        carrito.add(tour_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 160, -1));

        panel_bookActivities.add(carrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 650));

        title_informacion.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        title_informacion.setForeground(new java.awt.Color(0, 123, 164));
        title_informacion.setText("Informacion del cliente");
        panel_bookActivities.add(title_informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        btn_efectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dat_btn_Efectivo.png"))); // NOI18N
        btn_efectivo.setBorderPainted(false);
        btn_efectivo.setContentAreaFilled(false);
        btn_efectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_efectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_efectivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_efectivoMouseExited(evt);
            }
        });
        panel_bookActivities.add(btn_efectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 200, 50));

        btn_tarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dat_btn_Tarjeta.png"))); // NOI18N
        btn_tarjeta.setBorderPainted(false);
        btn_tarjeta.setContentAreaFilled(false);
        btn_tarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tarjetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tarjetaMouseExited(evt);
            }
        });
        panel_bookActivities.add(btn_tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 200, 50));

        btn_facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dat_btn_Factura.png"))); // NOI18N
        btn_facturacion.setBorderPainted(false);
        btn_facturacion.setContentAreaFilled(false);
        btn_facturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_facturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_facturacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_facturacionMouseExited(evt);
            }
        });
        btn_facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturacionActionPerformed(evt);
            }
        });
        panel_bookActivities.add(btn_facturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, 200, 50));

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Regresar.jpg"))); // NOI18N
        btn_regresar.setBorderPainted(false);
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_bookActivities.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 100, 50));

        btn_pagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Pagar.jpg"))); // NOI18N
        btn_pagar.setBorderPainted(false);
        btn_pagar.setContentAreaFilled(false);
        btn_pagar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_bookActivities.add(btn_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 590, 100, 50));

        title_nombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_nombre.setForeground(new java.awt.Color(153, 153, 153));
        title_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_nombre.setText("Nombre: ");
        panel_bookActivities.add(title_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        title_apellido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_apellido.setForeground(new java.awt.Color(153, 153, 153));
        title_apellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_apellido.setText("Apellido: ");
        panel_bookActivities.add(title_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        title_rfc.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_rfc.setForeground(new java.awt.Color(153, 153, 153));
        title_rfc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_rfc.setText("RFC");
        panel_bookActivities.add(title_rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        title_email.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_email.setForeground(new java.awt.Color(153, 153, 153));
        title_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_email.setText("Email: ");
        panel_bookActivities.add(title_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        title_numero.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_numero.setForeground(new java.awt.Color(153, 153, 153));
        title_numero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_numero.setText("Numero: ");
        panel_bookActivities.add(title_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        title_direccion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_direccion.setForeground(new java.awt.Color(153, 153, 153));
        title_direccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_direccion.setText("Direcc: ");
        panel_bookActivities.add(title_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        input_nombre.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_nombre.setForeground(new java.awt.Color(153, 153, 153));
        input_nombre.setBorder(null);
        panel_bookActivities.add(input_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 500, 30));

        input_apellido.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_apellido.setForeground(new java.awt.Color(153, 153, 153));
        input_apellido.setBorder(null);
        panel_bookActivities.add(input_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 500, 30));

        input_rfc.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_rfc.setForeground(new java.awt.Color(153, 153, 153));
        input_rfc.setBorder(null);
        panel_bookActivities.add(input_rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 500, 30));

        input_email.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_email.setForeground(new java.awt.Color(153, 153, 153));
        input_email.setBorder(null);
        panel_bookActivities.add(input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 500, 30));

        input_numero.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_numero.setForeground(new java.awt.Color(153, 153, 153));
        input_numero.setBorder(null);
        panel_bookActivities.add(input_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 500, 30));

        input_direccion.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_direccion.setForeground(new java.awt.Color(153, 153, 153));
        input_direccion.setBorder(null);
        panel_bookActivities.add(input_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 500, 30));
        panel_bookActivities.add(separador_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 510, 10));
        panel_bookActivities.add(separador_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 510, 10));
        panel_bookActivities.add(separador_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 510, 20));
        panel_bookActivities.add(separador_nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 510, 10));
        panel_bookActivities.add(separador_nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 510, 20));
        panel_bookActivities.add(separador_nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 510, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_bookActivities, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_bookActivities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_facturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_facturacionActionPerformed

    private void btn_efectivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_efectivoMouseEntered
        // TODO add your handling code here: 
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Efectivo_Select.png")); 
        this.btn_efectivo.setIcon(img);
    }//GEN-LAST:event_btn_efectivoMouseEntered

    private void btn_efectivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_efectivoMouseExited
        // TODO add your handling code here: 
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Efectivo.png")); 
        this.btn_efectivo.setIcon(img);
    }//GEN-LAST:event_btn_efectivoMouseExited

    private void btn_tarjetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tarjetaMouseEntered
        // TODO add your handling code here:  
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Tarjeta_Select.png")); 
        this.btn_tarjeta.setIcon(img);
        
    }//GEN-LAST:event_btn_tarjetaMouseEntered

    private void btn_tarjetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tarjetaMouseExited
        // TODO add your handling code here: 
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Tarjeta.png")); 
        this.btn_tarjeta.setIcon(img);
    }//GEN-LAST:event_btn_tarjetaMouseExited

    private void btn_facturacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_facturacionMouseEntered
        // TODO add your handling code here: 
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Factura_Select.png")); 
        this.btn_facturacion.setIcon(img);
    }//GEN-LAST:event_btn_facturacionMouseEntered

    private void btn_facturacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_facturacionMouseExited
        // TODO add your handling code here: 
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Factura.png")); 
        this.btn_facturacion.setIcon(img);
    }//GEN-LAST:event_btn_facturacionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_efectivo;
    private javax.swing.JButton btn_facturacion;
    private javax.swing.JButton btn_pagar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_tarjeta;
    private javax.swing.JPanel carrito;
    private javax.swing.JTextField input_apellido;
    private javax.swing.JTextField input_direccion;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_nombre;
    private javax.swing.JTextField input_numero;
    private javax.swing.JTextField input_rfc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel_bookActivities;
    private javax.swing.JSeparator separador_nombre;
    private javax.swing.JSeparator separador_nombre1;
    private javax.swing.JSeparator separador_nombre2;
    private javax.swing.JSeparator separador_nombre3;
    private javax.swing.JSeparator separador_nombre4;
    private javax.swing.JSeparator separador_nombre5;
    private javax.swing.JLabel title_adult;
    private javax.swing.JLabel title_apellido;
    private javax.swing.JLabel title_carrito;
    private javax.swing.JLabel title_child;
    private javax.swing.JLabel title_date;
    private javax.swing.JLabel title_direccion;
    private javax.swing.JLabel title_email;
    private javax.swing.JLabel title_informacion;
    private javax.swing.JLabel title_nombre;
    private javax.swing.JLabel title_numero;
    private javax.swing.JLabel title_rfc;
    private javax.swing.JLabel title_time1;
    private javax.swing.JLabel title_tour;
    private javax.swing.JLabel tour_adult;
    private javax.swing.JLabel tour_child;
    private javax.swing.JLabel tour_date;
    private javax.swing.JLabel tour_name;
    private javax.swing.JLabel tour_total;
    // End of variables declaration//GEN-END:variables
}
