/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import Classes.Prices;
import Classes.Tour;
import Conecction.Conecction;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Roman
 */
public class Windows extends javax.swing.JFrame {
    //Indica el precio final que pagara el cliente
    float precioTotal=0;
    //Variables para seguir la posicion del mouse y reajuste de ventana
     int x, y;
    String dateDB,date;
    private Conecction conn;
    int tipo=0;
    boolean flag=false;
    String time;
    ArrayList<Tour> tourAr = new ArrayList<Tour>();

    /**
     * Creates new form Windows
     */
    public Windows() {
        initComponents();
        this.conn = new Conecction();
        this.setLocationRelativeTo(this);
        tourAr=this.conn.getTours();
        panel_bookOpciones.setVisible(false);
        panel_bookActivities.setVisible(false);
        panel_bookClient.setVisible(false);
        java.util.Date fecha = new Date();
        this.Input_Date.setDate(fecha);
    }
    public Windows(String username){
        initComponents();
        this.user_name.setText("User: " + username);
        this.conn = new Conecction();
        this.setLocationRelativeTo(this);     
        tourAr=this.conn.getTours();
        panel_bookOpciones.setVisible(false);
        panel_bookActivities.setVisible(false);
        panel_bookClient.setVisible(false);
        java.util.Date fecha = new Date();
        this.Input_Date.setDate(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bookOpciones = new javax.swing.JPanel();
        input_infante = new javax.swing.JTextField();
        input_nino = new javax.swing.JTextField();
        input_adulto = new javax.swing.JTextField();
        btn_seguirComprando = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        btn_codigoPromocion = new javax.swing.JLabel();
        moneda = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        precio_infante = new javax.swing.JLabel();
        precio_nino = new javax.swing.JLabel();
        Input_Date = new com.toedter.calendar.JCalendar();
        Horario2 = new javax.swing.JToggleButton();
        Horario3 = new javax.swing.JToggleButton();
        Horario1 = new javax.swing.JToggleButton();
        precio_adulto = new javax.swing.JLabel();
        fondito6 = new javax.swing.JLabel();
        fondito5 = new javax.swing.JLabel();
        fondito4 = new javax.swing.JLabel();
        fondito3 = new javax.swing.JLabel();
        fondito2 = new javax.swing.JLabel();
        fondito1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_MX = new javax.swing.JToggleButton();
        btn_US = new javax.swing.JToggleButton();
        fondito7 = new javax.swing.JLabel();
        Extras_btn = new javax.swing.JToggleButton();
        multic = new javax.swing.JLabel();
        multic1 = new javax.swing.JLabel();
        multic2 = new javax.swing.JLabel();
        panel_drag = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JButton();
        btn_min = new javax.swing.JButton();
        Drager = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        panel_opciones = new javax.swing.JPanel();
        btn_terminos = new javax.swing.JButton();
        btn_cancelaciones = new javax.swing.JButton();
        btn_book = new javax.swing.JButton();
        user_name = new javax.swing.JLabel();
        guy = new javax.swing.JLabel();
        icon_guy = new javax.swing.JLabel();
        box23 = new javax.swing.JLabel();
        box = new javax.swing.JLabel();
        panel_bookActivities = new javax.swing.JPanel();
        btn_jungle = new javax.swing.JButton();
        btn_mangrove = new javax.swing.JButton();
        btn_scuba = new javax.swing.JButton();
        panel_Description = new javax.swing.JPanel();
        name_tour = new javax.swing.JLabel();
        moneda1 = new javax.swing.JLabel();
        moneda2 = new javax.swing.JLabel();
        btn_cancelar1 = new javax.swing.JButton();
        btn_siguiente1 = new javax.swing.JButton();
        description = new javax.swing.JLabel();
        title_child = new javax.swing.JLabel();
        title_adult = new javax.swing.JLabel();
        child_price = new javax.swing.JLabel();
        adult_price = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();
        img_tour = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel_bookClient = new javax.swing.JPanel();
        carrito = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        title_carrito = new javax.swing.JLabel();
        title_tour = new javax.swing.JLabel();
        title_date = new javax.swing.JLabel();
        title_adult1 = new javax.swing.JLabel();
        title_child1 = new javax.swing.JLabel();
        title_time1 = new javax.swing.JLabel();
        tour_Time = new javax.swing.JLabel();
        tour_name = new javax.swing.JLabel();
        tour_date = new javax.swing.JLabel();
        tour_adult = new javax.swing.JLabel();
        tour_child = new javax.swing.JLabel();
        tour_total = new javax.swing.JLabel();
        title_infate = new javax.swing.JLabel();
        tour_infante = new javax.swing.JLabel();
        title_informacion = new javax.swing.JLabel();
        btn_tarjeta = new javax.swing.JButton();
        btn_facturacion = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        btn_pagar = new javax.swing.JButton();
        title_nombre = new javax.swing.JLabel();
        title_apellido = new javax.swing.JLabel();
        title_rfc = new javax.swing.JLabel();
        title_email = new javax.swing.JLabel();
        title_numero = new javax.swing.JLabel();
        title_direccion = new javax.swing.JLabel();
        input_nombre = new javax.swing.JTextField();
        input_apellido = new javax.swing.JTextField();
        input_rfc = new javax.swing.JTextField();
        input_email = new javax.swing.JTextField();
        input_numero = new javax.swing.JTextField();
        input_direccion = new javax.swing.JTextField();
        separador_nombre = new javax.swing.JSeparator();
        separador_nombre1 = new javax.swing.JSeparator();
        separador_nombre2 = new javax.swing.JSeparator();
        separador_nombre3 = new javax.swing.JSeparator();
        separador_nombre4 = new javax.swing.JSeparator();
        separador_nombre5 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        btn_efectivo = new javax.swing.JToggleButton();
        efectivo_label = new javax.swing.JLabel();
        panel_pasos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fondo_pasos = new javax.swing.JLabel();
        GeneralBG = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_bookOpciones.setBackground(new java.awt.Color(255, 255, 255));
        panel_bookOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_bookOpcionesMouseEntered(evt);
            }
        });
        panel_bookOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input_infante.setBackground(new java.awt.Color(240, 240, 240));
        input_infante.setFont(new java.awt.Font("Roboto", 0, 55)); // NOI18N
        input_infante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_infante.setText("0");
        input_infante.setAutoscrolls(false);
        input_infante.setBorder(null);
        input_infante.setOpaque(false);
        input_infante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_infanteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_infanteFocusLost(evt);
            }
        });
        panel_bookOpciones.add(input_infante, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 60, 60));

        input_nino.setBackground(new java.awt.Color(240, 240, 240));
        input_nino.setFont(new java.awt.Font("Roboto", 0, 55)); // NOI18N
        input_nino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_nino.setText("0");
        input_nino.setAutoscrolls(false);
        input_nino.setBorder(null);
        input_nino.setOpaque(false);
        input_nino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_ninoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_ninoFocusLost(evt);
            }
        });
        panel_bookOpciones.add(input_nino, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, 60, 60));

        input_adulto.setBackground(new java.awt.Color(240, 240, 240));
        input_adulto.setFont(new java.awt.Font("Roboto", 0, 55)); // NOI18N
        input_adulto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_adulto.setText("0");
        input_adulto.setAutoscrolls(false);
        input_adulto.setBorder(null);
        input_adulto.setOpaque(false);
        input_adulto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_adultoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_adultoFocusLost(evt);
            }
        });
        panel_bookOpciones.add(input_adulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, 60, 60));

        btn_seguirComprando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Comprar.jpg"))); // NOI18N
        btn_seguirComprando.setBorderPainted(false);
        btn_seguirComprando.setContentAreaFilled(false);
        btn_seguirComprando.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_bookOpciones.add(btn_seguirComprando, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 670, 160, 50));

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Cancelar.jpg"))); // NOI18N
        btn_cancelar.setBorderPainted(false);
        btn_cancelar.setContentAreaFilled(false);
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        panel_bookOpciones.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 670, 100, 50));

        btn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Siguiente.jpg"))); // NOI18N
        btn_siguiente.setBorderPainted(false);
        btn_siguiente.setContentAreaFilled(false);
        btn_siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });
        panel_bookOpciones.add(btn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 670, 100, 50));

        btn_codigoPromocion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_codigoPromocion.setForeground(new java.awt.Color(51, 153, 255));
        btn_codigoPromocion.setText("Codigo de promocion");
        btn_codigoPromocion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_bookOpciones.add(btn_codigoPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 620, -1, -1));

        moneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_btn_mx.png"))); // NOI18N
        moneda.setToolTipText("");
        panel_bookOpciones.add(moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 590, -1, -1));

        totalPrice.setFont(new java.awt.Font("Roboto", 0, 62)); // NOI18N
        totalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPrice.setText("$000.00");
        panel_bookOpciones.add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, 400, -1));

        precio_infante.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        precio_infante.setForeground(new java.awt.Color(255, 255, 255));
        precio_infante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precio_infante.setText("$0000");
        panel_bookOpciones.add(precio_infante, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 350, 80, -1));

        precio_nino.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        precio_nino.setForeground(new java.awt.Color(255, 255, 255));
        precio_nino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precio_nino.setText("$0000");
        panel_bookOpciones.add(precio_nino, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, 80, -1));

        Input_Date.setDate(new java.util.Date(1508776872000L));
        Input_Date.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Input_Date.setWeekOfYearVisible(false);
        panel_bookOpciones.add(Input_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 430, 340));

        Horario2.setBackground(new java.awt.Color(204, 204, 204));
        Horario2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Horario2.setText("00:00 Hrs");
        Horario2.setBorderPainted(false);
        Horario2.setOpaque(true);
        Horario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Horario2ActionPerformed(evt);
            }
        });
        panel_bookOpciones.add(Horario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, -1, -1));

        Horario3.setBackground(new java.awt.Color(204, 204, 204));
        Horario3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Horario3.setText("00:00 Hrs");
        Horario3.setBorderPainted(false);
        Horario3.setOpaque(true);
        Horario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Horario3ActionPerformed(evt);
            }
        });
        panel_bookOpciones.add(Horario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 550, -1, -1));

        Horario1.setBackground(new java.awt.Color(204, 204, 204));
        Horario1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Horario1.setText("00:00 Hrs");
        Horario1.setBorderPainted(false);
        Horario1.setOpaque(true);
        Horario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Horario1ActionPerformed(evt);
            }
        });
        panel_bookOpciones.add(Horario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        precio_adulto.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        precio_adulto.setForeground(new java.awt.Color(255, 255, 255));
        precio_adulto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precio_adulto.setText("$0000");
        panel_bookOpciones.add(precio_adulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 150, 80, -1));

        fondito6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Price.jpg"))); // NOI18N
        panel_bookOpciones.add(fondito6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 320, -1, -1));

        fondito5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Price.jpg"))); // NOI18N
        panel_bookOpciones.add(fondito5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, -1, -1));

        fondito4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Price.jpg"))); // NOI18N
        panel_bookOpciones.add(fondito4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 120, -1, -1));

        fondito3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Description.jpg"))); // NOI18N
        panel_bookOpciones.add(fondito3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, -1, -1));

        fondito2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Description.jpg"))); // NOI18N
        panel_bookOpciones.add(fondito2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, -1, -1));

        fondito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Description.jpg"))); // NOI18N
        fondito1.setOpaque(true);
        panel_bookOpciones.add(fondito1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, -1, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel18.setText("Infante");
        panel_bookOpciones.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, -1, 40));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel17.setText("Niño");
        panel_bookOpciones.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 60, 40));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel16.setText("Adulto");
        panel_bookOpciones.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, -1, 40));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 123, 164));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Total");
        panel_bookOpciones.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 500, 610, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 123, 164));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Hora");
        panel_bookOpciones.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 690, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 123, 164));
        jLabel10.setText("Precio");
        panel_bookOpciones.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 123, 164));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Día");
        panel_bookOpciones.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 690, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Box_Day.jpg"))); // NOI18N
        panel_bookOpciones.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 700, 470));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Box_Hour.jpg"))); // NOI18N
        panel_bookOpciones.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        btn_MX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_btn_mx.png"))); // NOI18N
        btn_MX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MXActionPerformed(evt);
            }
        });
        panel_bookOpciones.add(btn_MX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 60, 30));

        btn_US.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_btn_usd.png"))); // NOI18N
        btn_US.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_USActionPerformed(evt);
            }
        });
        panel_bookOpciones.add(btn_US, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, 60, 30));

        fondito7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Price.jpg"))); // NOI18N
        panel_bookOpciones.add(fondito7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 120, -1, -1));

        Extras_btn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Extras_btn.setForeground(new java.awt.Color(153, 153, 153));
        Extras_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_PersonPlus.png"))); // NOI18N
        Extras_btn.setText("Extras");
        panel_bookOpciones.add(Extras_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, 140, 40));

        multic.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        multic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multic.setText("X");
        panel_bookOpciones.add(multic, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 330, 60, 60));

        multic1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        multic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multic1.setText("X");
        panel_bookOpciones.add(multic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 60, 60));

        multic2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        multic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multic2.setText("X");
        panel_bookOpciones.add(multic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 60, 60));

        getContentPane().add(panel_bookOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 1300, 760));

        panel_drag.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Cerrar_1_Normal.png"))); // NOI18N
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        panel_drag.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 0, 50, 40));

        btn_min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Recurso 100_Normal.png"))); // NOI18N
        btn_min.setContentAreaFilled(false);
        btn_min.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minActionPerformed(evt);
            }
        });
        panel_drag.add(btn_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 50, 40));

        Drager.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Drager.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragerMouseDragged(evt);
            }
        });
        Drager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragerMousePressed(evt);
            }
        });
        panel_drag.add(Drager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TB_Bar.jpg"))); // NOI18N
        BG.setPreferredSize(new java.awt.Dimension(1600, 42));
        panel_drag.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        getContentPane().add(panel_drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 40));

        panel_opciones.setBackground(new java.awt.Color(204, 255, 204));
        panel_opciones.setMinimumSize(new java.awt.Dimension(300, 840));
        panel_opciones.setPreferredSize(new java.awt.Dimension(300, 840));
        panel_opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_terminos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_TC_Static.png"))); // NOI18N
        btn_terminos.setBorderPainted(false);
        btn_terminos.setContentAreaFilled(false);
        btn_terminos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_terminos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_terminosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_terminosMouseExited(evt);
            }
        });
        btn_terminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminosActionPerformed(evt);
            }
        });
        panel_opciones.add(btn_terminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, -1));

        btn_cancelaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Cancel_Static.png"))); // NOI18N
        btn_cancelaciones.setBorderPainted(false);
        btn_cancelaciones.setContentAreaFilled(false);
        btn_cancelaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cancelaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelacionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelacionesMouseExited(evt);
            }
        });
        btn_cancelaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelacionesActionPerformed(evt);
            }
        });
        panel_opciones.add(btn_cancelaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 300, -1));

        btn_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Book_Static.png"))); // NOI18N
        btn_book.setBorderPainted(false);
        btn_book.setContentAreaFilled(false);
        btn_book.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bookMouseExited(evt);
            }
        });
        btn_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookActionPerformed(evt);
            }
        });
        panel_opciones.add(btn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 300, -1));

        user_name.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        user_name.setForeground(new java.awt.Color(255, 255, 255));
        user_name.setText("Nombre de Usuario");
        panel_opciones.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 220, -1));

        guy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/Icn_MPE.png"))); // NOI18N
        panel_opciones.add(guy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -14, 70, 110));

        icon_guy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Icn_ContactBubble.png"))); // NOI18N
        panel_opciones.add(icon_guy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        box23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Box_Left_Extended.png"))); // NOI18N
        panel_opciones.add(box23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 90, 890));

        box.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Box_Left_Extended.png"))); // NOI18N
        box.setMaximumSize(new java.awt.Dimension(300, 830));
        box.setMinimumSize(new java.awt.Dimension(300, 830));
        box.setPreferredSize(new java.awt.Dimension(300, 830));
        panel_opciones.add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 850));

        getContentPane().add(panel_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, -1));

        panel_bookActivities.setBackground(new java.awt.Color(255, 255, 255));
        panel_bookActivities.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_jungle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Jungle01_Static.jpg"))); // NOI18N
        btn_jungle.setBorderPainted(false);
        btn_jungle.setContentAreaFilled(false);
        btn_jungle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_jungle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_jungleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_jungleMouseExited(evt);
            }
        });
        btn_jungle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jungleActionPerformed(evt);
            }
        });
        panel_bookActivities.add(btn_jungle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 370, -1));

        btn_mangrove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mangroove_Static.jpg"))); // NOI18N
        btn_mangrove.setBorderPainted(false);
        btn_mangrove.setContentAreaFilled(false);
        btn_mangrove.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_mangrove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mangroveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mangroveMouseExited(evt);
            }
        });
        btn_mangrove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mangroveActionPerformed(evt);
            }
        });
        panel_bookActivities.add(btn_mangrove, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 370, -1));

        btn_scuba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Scuba_Static.jpg"))); // NOI18N
        btn_scuba.setBorderPainted(false);
        btn_scuba.setContentAreaFilled(false);
        btn_scuba.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_scuba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_scubaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_scubaMouseExited(evt);
            }
        });
        btn_scuba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scubaActionPerformed(evt);
            }
        });
        panel_bookActivities.add(btn_scuba, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 370, -1));

        panel_Description.setBackground(new java.awt.Color(222, 222, 222));
        panel_Description.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_tour.setFont(new java.awt.Font("Roboto Lt", 0, 48)); // NOI18N
        name_tour.setForeground(new java.awt.Color(255, 255, 255));
        panel_Description.add(name_tour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 510, 60));

        moneda1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        moneda1.setForeground(new java.awt.Color(255, 255, 255));
        moneda1.setText("USD");
        panel_Description.add(moneda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 227, -1, 10));

        moneda2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        moneda2.setForeground(new java.awt.Color(255, 255, 255));
        moneda2.setText("USD");
        panel_Description.add(moneda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 227, -1, 10));

        btn_cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Cancelar.jpg"))); // NOI18N
        btn_cancelar1.setBorderPainted(false);
        btn_cancelar1.setContentAreaFilled(false);
        btn_cancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelar1MouseExited(evt);
            }
        });
        btn_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar1ActionPerformed(evt);
            }
        });
        panel_Description.add(btn_cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, 100, 50));

        btn_siguiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Siguiente.jpg"))); // NOI18N
        btn_siguiente1.setBorderPainted(false);
        btn_siguiente1.setContentAreaFilled(false);
        btn_siguiente1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_siguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_siguiente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_siguiente1MouseExited(evt);
            }
        });
        btn_siguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguiente1ActionPerformed(evt);
            }
        });
        panel_Description.add(btn_siguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, 100, 50));

        description.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        description.setForeground(new java.awt.Color(153, 153, 153));
        panel_Description.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 500, 500));

        title_child.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_child.setForeground(new java.awt.Color(255, 255, 255));
        title_child.setText("Child");
        panel_Description.add(title_child, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        title_adult.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_adult.setForeground(new java.awt.Color(255, 255, 255));
        title_adult.setText("Adult");
        panel_Description.add(title_adult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        child_price.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        child_price.setForeground(new java.awt.Color(255, 255, 255));
        child_price.setText("$00.00");
        panel_Description.add(child_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        adult_price.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        adult_price.setForeground(new java.awt.Color(255, 255, 255));
        adult_price.setText("$00.00");
        panel_Description.add(adult_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        banner.setToolTipText("");
        panel_Description.add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 510, 100));
        panel_Description.add(img_tour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 180));

        panel_bookActivities.add(panel_Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 0, -1, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BoatRental_Static.jpg"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_bookActivities.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 370, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Aquabus_Static.jpg"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_bookActivities.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 370, -1));

        getContentPane().add(panel_bookActivities, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 1300, 760));

        panel_bookClient.setBackground(new java.awt.Color(255, 255, 255));
        panel_bookClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carrito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        carrito.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 490, 10));

        title_carrito.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        title_carrito.setForeground(new java.awt.Color(0, 123, 164));
        title_carrito.setText("Carrito");
        carrito.add(title_carrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        title_tour.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_tour.setForeground(new java.awt.Color(153, 153, 153));
        title_tour.setText("Tour: ");
        carrito.add(title_tour, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        title_date.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_date.setForeground(new java.awt.Color(153, 153, 153));
        title_date.setText("Date:");
        carrito.add(title_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        title_adult1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_adult1.setForeground(new java.awt.Color(153, 153, 153));
        title_adult1.setText("Adult:");
        carrito.add(title_adult1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        title_child1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_child1.setForeground(new java.awt.Color(153, 153, 153));
        title_child1.setText("Child:");
        carrito.add(title_child1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        title_time1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_time1.setForeground(new java.awt.Color(153, 153, 153));
        title_time1.setText("Time:");
        carrito.add(title_time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        tour_Time.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_Time.setForeground(new java.awt.Color(153, 153, 153));
        tour_Time.setText("00:00 hrs");
        carrito.add(tour_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 120, -1));

        tour_name.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_name.setForeground(new java.awt.Color(153, 153, 153));
        tour_name.setText("Tour Mane");
        carrito.add(tour_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 240, -1));

        tour_date.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_date.setForeground(new java.awt.Color(153, 153, 153));
        tour_date.setText("00-month-0000");
        carrito.add(tour_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 250, -1));

        tour_adult.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_adult.setForeground(new java.awt.Color(153, 153, 153));
        tour_adult.setText("00");
        carrito.add(tour_adult, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 50, -1));

        tour_child.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_child.setForeground(new java.awt.Color(153, 153, 153));
        tour_child.setText("00");
        carrito.add(tour_child, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 50, -1));

        tour_total.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        tour_total.setForeground(new java.awt.Color(0, 102, 255));
        tour_total.setText("$0000.00 USD");
        carrito.add(tour_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 160, -1));

        title_infate.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_infate.setForeground(new java.awt.Color(153, 153, 153));
        title_infate.setText("Infante:");
        carrito.add(title_infate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        tour_infante.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_infante.setForeground(new java.awt.Color(153, 153, 153));
        tour_infante.setText("00");
        carrito.add(tour_infante, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 50, -1));

        panel_bookClient.add(carrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 760));

        title_informacion.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        title_informacion.setForeground(new java.awt.Color(0, 123, 164));
        title_informacion.setText("Informacion del cliente");
        panel_bookClient.add(title_informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        btn_tarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dat_btn_Tarjeta.png"))); // NOI18N
        btn_tarjeta.setBorderPainted(false);
        btn_tarjeta.setContentAreaFilled(false);
        btn_tarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_tarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tarjetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tarjetaMouseExited(evt);
            }
        });
        btn_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tarjetaActionPerformed(evt);
            }
        });
        panel_bookClient.add(btn_tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 200, 50));

        btn_facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dat_btn_Factura.png"))); // NOI18N
        btn_facturacion.setBorderPainted(false);
        btn_facturacion.setContentAreaFilled(false);
        btn_facturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_facturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_facturacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_facturacionMouseExited(evt);
            }
        });
        btn_facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturacionActionPerformed(evt);
            }
        });
        panel_bookClient.add(btn_facturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, 200, 50));

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Regresar.jpg"))); // NOI18N
        btn_regresar.setBorderPainted(false);
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        panel_bookClient.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, -1, 50));

        btn_pagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Pagar.jpg"))); // NOI18N
        btn_pagar.setBorderPainted(false);
        btn_pagar.setContentAreaFilled(false);
        btn_pagar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagarActionPerformed(evt);
            }
        });
        panel_bookClient.add(btn_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 620, 100, 50));

        title_nombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_nombre.setForeground(new java.awt.Color(153, 153, 153));
        title_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_nombre.setText("Nombre: ");
        panel_bookClient.add(title_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        title_apellido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_apellido.setForeground(new java.awt.Color(153, 153, 153));
        title_apellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_apellido.setText("Apellido: ");
        panel_bookClient.add(title_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        title_rfc.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_rfc.setForeground(new java.awt.Color(153, 153, 153));
        title_rfc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_rfc.setText("RFC");
        panel_bookClient.add(title_rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        title_email.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_email.setForeground(new java.awt.Color(153, 153, 153));
        title_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_email.setText("Email: ");
        panel_bookClient.add(title_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        title_numero.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_numero.setForeground(new java.awt.Color(153, 153, 153));
        title_numero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_numero.setText("Numero: ");
        panel_bookClient.add(title_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        title_direccion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_direccion.setForeground(new java.awt.Color(153, 153, 153));
        title_direccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_direccion.setText("Direcc: ");
        panel_bookClient.add(title_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, -1));

        input_nombre.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_nombre.setForeground(new java.awt.Color(153, 153, 153));
        input_nombre.setBorder(null);
        panel_bookClient.add(input_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 500, 30));

        input_apellido.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_apellido.setForeground(new java.awt.Color(153, 153, 153));
        input_apellido.setBorder(null);
        panel_bookClient.add(input_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 500, 30));

        input_rfc.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_rfc.setForeground(new java.awt.Color(153, 153, 153));
        input_rfc.setBorder(null);
        panel_bookClient.add(input_rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 500, 30));

        input_email.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_email.setForeground(new java.awt.Color(153, 153, 153));
        input_email.setBorder(null);
        panel_bookClient.add(input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 500, 30));

        input_numero.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_numero.setForeground(new java.awt.Color(153, 153, 153));
        input_numero.setBorder(null);
        panel_bookClient.add(input_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 500, 30));

        input_direccion.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_direccion.setForeground(new java.awt.Color(153, 153, 153));
        input_direccion.setBorder(null);
        panel_bookClient.add(input_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 500, 30));
        panel_bookClient.add(separador_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 510, 10));
        panel_bookClient.add(separador_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 510, 10));
        panel_bookClient.add(separador_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 510, 20));
        panel_bookClient.add(separador_nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 510, 10));
        panel_bookClient.add(separador_nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 510, 20));
        panel_bookClient.add(separador_nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 510, 40));

        jToggleButton1.setText("jToggleButton1");
        panel_bookClient.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 200, -1));

        jToggleButton2.setText("jToggleButton1");
        panel_bookClient.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, 200, -1));

        btn_efectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dat_btn_Efectivo.png"))); // NOI18N
        btn_efectivo.setContentAreaFilled(false);
        btn_efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_efectivoActionPerformed(evt);
            }
        });
        panel_bookClient.add(btn_efectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 200, 50));

        efectivo_label.setBackground(new java.awt.Color(255, 51, 204));
        efectivo_label.setForeground(new java.awt.Color(153, 153, 0));
        efectivo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Background.png"))); // NOI18N
        panel_bookClient.add(efectivo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 180, 50));

        getContentPane().add(panel_bookClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 1300, 760));

        panel_pasos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Icn_Divider.png"))); // NOI18N
        panel_pasos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 20, -1));

        fondo_pasos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Main_TopBar.png"))); // NOI18N
        fondo_pasos.setMaximumSize(new java.awt.Dimension(1300, 80));
        fondo_pasos.setMinimumSize(new java.awt.Dimension(1300, 80));
        fondo_pasos.setPreferredSize(new java.awt.Dimension(1300, 80));
        panel_pasos.add(fondo_pasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1320, 80));

        getContentPane().add(panel_pasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 1300, 80));

        GeneralBG.setBackground(new java.awt.Color(255, 255, 255));
        GeneralBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/MarinaPuntadelEste_Logo.png"))); // NOI18N
        GeneralBG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 860, 480));

        getContentPane().add(GeneralBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 1300, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void DragerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragerMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_DragerMouseDragged

    private void DragerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragerMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_DragerMousePressed

    private void btn_terminosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_terminosMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Btn_TC_Hover.png"));
        btn_terminos.setIcon(img);
    }//GEN-LAST:event_btn_terminosMouseEntered

    private void btn_terminosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_terminosMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Btn_TC_Static.png"));
        btn_terminos.setIcon(img);
    }//GEN-LAST:event_btn_terminosMouseExited

    private void btn_terminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminosActionPerformed
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Btn_TC_Active.png"));
        btn_terminos.setIcon(img);
    }//GEN-LAST:event_btn_terminosActionPerformed

    private void btn_cancelacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelacionesMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Btn_Cancel_Hover.png"));
        btn_cancelaciones.setIcon(img);
    }//GEN-LAST:event_btn_cancelacionesMouseEntered

    private void btn_cancelacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelacionesMouseExited
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Btn_Cancel_Static.png"));
        btn_cancelaciones.setIcon(img);
    }//GEN-LAST:event_btn_cancelacionesMouseExited

    private void btn_cancelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelacionesActionPerformed
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Btn_Cancel_Active.png"));
        btn_cancelaciones.setIcon(img);
    }//GEN-LAST:event_btn_cancelacionesActionPerformed

    private void btn_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bookMouseEntered
        if (!this.panel_bookOpciones.isVisible()){
            ImageIcon img = new ImageIcon(getClass().getResource("/img/Btn_Book_Hover.png"));
            btn_book.setIcon(img);
        }
    }//GEN-LAST:event_btn_bookMouseEntered

    private void btn_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bookMouseExited
        if (!flag){
            ImageIcon img = new ImageIcon(getClass().getResource("/img/Btn_Book_Static.png"));
            btn_book.setIcon(img);
        }
    }//GEN-LAST:event_btn_bookMouseExited

    private void btn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookActionPerformed
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Btn_Book_Active.png"));
        btn_book.setIcon(img);
        flag=true;
        panel_bookActivities.setVisible(true);
        this.panel_Description.setVisible(false);
        panel_bookOpciones.setVisible(false);
        panel_bookClient.setVisible(false);
        this.jButton1.setVisible(true);
        this.jButton2.setVisible(true);
    }//GEN-LAST:event_btn_bookActionPerformed

    private void btn_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar1ActionPerformed
        // TODO add your handling code here:
        tipo=0; 
        ImageIcon nepe = new ImageIcon(getClass().getResource("/img/Btn_Cancelar_Active.png"));
        btn_cancelar1.setIcon(nepe);
        this.jButton1.setVisible(true);
        this.jButton2.setVisible(true);
        ImageIcon img = new ImageIcon(getClass().getResource(""));
        ImageIcon ban = new ImageIcon(getClass().getResource(""));
        img_tour.setIcon(img);
        banner.setIcon(ban);
        name_tour.setText("");
        adult_price.setText("");//BD
        child_price.setText("");
        description.setText("");
        panel_Description.setVisible(false);
    }//GEN-LAST:event_btn_cancelar1ActionPerformed

    private void btn_siguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguiente1ActionPerformed
        // TODO add your handling code here: 
        ImageIcon nepe = new ImageIcon(getClass().getResource("/img/Btn_Sig_Active.png"));
        
        btn_siguiente1.setIcon(nepe);
        panel_bookOpciones.setVisible(true);
        panel_bookActivities.setVisible(false);
        //SE PRESIONA EL BOTON US POR QUE DOLAR ES POR DEFECTO
        if(this.btn_MX.isSelected())
            this.btn_MX.setSelected(false);
        
        this.precio_adulto.setText(Float.toString(this.tourAr.get(tipo-1).precioAdultoUS));
        this.precio_nino.setText(Float.toString(this.tourAr.get(tipo-1).precioNinoUS));
        this.precio_infante.setText(Float.toString(this.tourAr.get(tipo-1).precioInfanteUS));
        float A=Float.parseFloat(this.input_adulto.getText())*Float.parseFloat(this.precio_adulto.getText());
        float P=Float.parseFloat(this.input_nino.getText())*Float.parseFloat(this.precio_nino.getText());
        float D=Float.parseFloat(this.input_infante.getText())*Float.parseFloat(this.precio_infante.getText());
        this.totalPrice.setText("$ "+Float.toString(A+P+D));
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Ag_btn_usd.png"));
        moneda.setIcon(img); 
        //SE TERMINA EL PRESIONADO DE DOLAR
        this.btn_US.setSelected(true);
        Horario1.setText(this.tourAr.get(tipo-1).hora1.substring(0,5)+ " Hrs");
        Horario2.setText(this.tourAr.get(tipo-1).hora2.substring(0,5)+" Hrs");
        Horario3.setText(this.tourAr.get(tipo-1).hora3.substring(0,5)+" Hrs");
        //Siempre al entrar se setean en null para que no tome nada de la anterior compra
        date = null;
        dateDB = null;
    }//GEN-LAST:event_btn_siguiente1ActionPerformed

    private void btn_jungleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jungleActionPerformed
        // TODO add your handling code here 
        ImageIcon nepe =  new ImageIcon(getClass().getResource("/img/Jungle01_Select.jpg")); 
        this.btn_jungle.setIcon(nepe); 
        this.jButton1.setVisible(false);
        this.jButton2.setVisible(false);
        this.panel_Description.setVisible(false);
        tipo = 1;
        this.adult_price.setText("$ "+Float.toString(this.tourAr.get(0).precioAdultoUS));
        this.child_price.setText("$ "+Float.toString(this.tourAr.get(0).precioNinoUS));
        panel_Description.setVisible(true);
        ImageIcon img = new ImageIcon(getClass().getResource("/img/JungleTour.jpg"));
        ImageIcon ban = new ImageIcon(getClass().getResource("/img/A_BigBar_Green_02.png"));
        img_tour.setIcon(img);
        banner.setIcon(ban);
        name_tour.setText("Jungle Tour");
        description.setText("<html><p>Get to drive your own speedboat on Cancun’s signature snorkel tour. "
            + "The adventure starts off by steering through the dense mangroves onto Punta Nizuc’s Coral Reef, "
            + "where you will be able to snorkel and discover the astonishing sea life!</p> "
            + "<br><p>What’s included</p><p>-Speedboat ride (Up to two pax per boat – there will be an extra charge for a single rides. Families may ask for a 4 pax boat).</p>"
            + "<p>-Snorkel gear.</p><p>-Bilingual tour guide.</p><p>-Bottled water.</p><p>-Locker</p><br><p>Does not include</p><p>-Dock [fee $10 usd.]</p><p>-Photos</p><p>-Tips</p></html>");
    }//GEN-LAST:event_btn_jungleActionPerformed

    private void btn_mangroveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mangroveActionPerformed
        // TODO add your handling code here: 
        ImageIcon nepe =  new ImageIcon(getClass().getResource("/img/Mangroove_Select.jpg")); 
        this.btn_mangrove.setIcon(nepe); 
        this.jButton1.setVisible(false);
        this.jButton2.setVisible(false);
        this.panel_Description.setVisible(false);
        tipo=2;
        this.adult_price.setText("$ "+Float.toString(this.tourAr.get(1).precioAdultoUS));
        this.child_price.setText("$ "+Float.toString(this.tourAr.get(1).precioNinoUS));
        panel_Description.setVisible(true);
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Mangroove.jpg"));
        ImageIcon ban = new ImageIcon(getClass().getResource("/img/A_BigBar_Green_03.png"));
        img_tour.setIcon(img);
        banner.setIcon(ban);
        name_tour.setText("Mangrove  Tour");
        description.setText("<html><p>Enjoy the thrill of driving your own speedboat while enjoying the sight of mangroves and local wildlife. Stopping for a refreshing swim at “Playa Conchitas”.</p> "
            + "<p>Duration 1.40h</p><br><p>What’s included</p><p>-Speedboat ride (Up to two pax per boat – there will be an extra charge for a single rides. Families may ask for a 4 pax boat).</p>"
            + "<p>-Snorkel gear.</p><p>-Bilingual tour guide.</p><p>-Bottled water.</p><p>-Locker</p><br><p>Does not include</p><p>-Dock [fee $10 usd.]</p><p>-Photos</p><p>-Tips</p></html>");
    }//GEN-LAST:event_btn_mangroveActionPerformed

    private void btn_scubaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scubaActionPerformed
        // TODO add your handling code here: 
        ImageIcon nepe =  new ImageIcon(getClass().getResource("/img/Scuba_Select.jpg")); 
        this.btn_scuba.setIcon(nepe); 
        this.jButton1.setVisible(false);
        this.jButton2.setVisible(false);
        this.panel_Description.setVisible(false);
        tipo=3;
        this.adult_price.setText("$ "+Float.toString(this.tourAr.get(2).precioAdultoUS));
        this.child_price.setText("$ "+Float.toString(this.tourAr.get(2).precioNinoUS));
        panel_Description.setVisible(true);
        ImageIcon img = new ImageIcon(getClass().getResource("/img/ScubaDive.jpg"));
        ImageIcon ban = new ImageIcon(getClass().getResource("/img/A_BigBar_Blue_01.png"));
        img_tour.setIcon(img);
        banner.setIcon(ban);
        name_tour.setText("Scuba Dive");
        description.setText("<html><p>Enjoy the thrill of driving your own speedboat while enjoying the sight of mangroves and local wildlife. Stopping for a refreshing swim at “Playa Conchitas”.</p> "
            + "<p>Duration 1.40h</p><br><p>What’s included</p><p>-Speedboat ride (Up to two pax per boat – there will be an extra charge for a single rides. Families may ask for a 4 pax boat).</p>"
            + "<p>-Snorkel gear.</p><p>-Bilingual tour guide.</p><p>-Bottled water.</p><p>-Locker</p><br><p>Does not include</p><p>-Dock [fee $10 usd.]</p><p>-Photos</p><p>-Tips</p></html>");
    }//GEN-LAST:event_btn_scubaActionPerformed

    private void input_adultoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_adultoFocusGained
        // TODO add your handling code here:
        float A=Float.parseFloat(this.input_adulto.getText())*Float.parseFloat(this.precio_adulto.getText());
        float P=Float.parseFloat(this.input_nino.getText())*Float.parseFloat(this.precio_nino.getText());
        float D=Float.parseFloat(this.input_infante.getText())*Float.parseFloat(this.precio_infante.getText());
        this.totalPrice.setText("$ "+Float.toString(A+P+D));
    }//GEN-LAST:event_input_adultoFocusGained

    private void input_ninoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_ninoFocusGained
        // TODO add your handling code here:
         float A=Float.parseFloat(this.input_adulto.getText())*Float.parseFloat(this.precio_adulto.getText());
        float P=Float.parseFloat(this.input_nino.getText())*Float.parseFloat(this.precio_nino.getText());
        float D=Float.parseFloat(this.input_infante.getText())*Float.parseFloat(this.precio_infante.getText());
        this.totalPrice.setText("$ "+Float.toString(A+P+D));
    }//GEN-LAST:event_input_ninoFocusGained

    private void input_infanteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_infanteFocusGained
        // TODO add your handling code here:
         float A=Float.parseFloat(this.input_adulto.getText())*Float.parseFloat(this.precio_adulto.getText());
        float P=Float.parseFloat(this.input_nino.getText())*Float.parseFloat(this.precio_nino.getText());
        float D=Float.parseFloat(this.input_infante.getText())*Float.parseFloat(this.precio_infante.getText());
        this.totalPrice.setText("$ "+Float.toString(A+P+D));
    }//GEN-LAST:event_input_infanteFocusGained

    private void input_adultoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_adultoFocusLost
        // TODO add your handling code here:
        float A=Float.parseFloat(this.input_adulto.getText())*Float.parseFloat(this.precio_adulto.getText());
        float P=Float.parseFloat(this.input_nino.getText())*Float.parseFloat(this.precio_nino.getText());
        float D=Float.parseFloat(this.input_infante.getText())*Float.parseFloat(this.precio_infante.getText());
        this.totalPrice.setText("$ "+Float.toString(A+P+D));
    }//GEN-LAST:event_input_adultoFocusLost

    private void input_ninoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_ninoFocusLost

        // TODO add your handling code here:
        float A=Float.parseFloat(this.input_adulto.getText())*Float.parseFloat(this.precio_adulto.getText());
        float P=Float.parseFloat(this.input_nino.getText())*Float.parseFloat(this.precio_nino.getText());
        float D=Float.parseFloat(this.input_infante.getText())*Float.parseFloat(this.precio_infante.getText());
        this.totalPrice.setText("$ "+Float.toString(A+P+D));
    }//GEN-LAST:event_input_ninoFocusLost

    private void input_infanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_infanteFocusLost
float A=Float.parseFloat(this.input_adulto.getText())*Float.parseFloat(this.precio_adulto.getText());
        float P=Float.parseFloat(this.input_nino.getText())*Float.parseFloat(this.precio_nino.getText());
        float D=Float.parseFloat(this.input_infante.getText())*Float.parseFloat(this.precio_infante.getText());
        this.totalPrice.setText("$ "+Float.toString(A+P+D));        // TODO add your handling code here:
    }//GEN-LAST:event_input_infanteFocusLost

    private void panel_bookOpcionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_bookOpcionesMouseEntered
        // TODO add your handling code here:
        float A=Float.parseFloat(this.input_adulto.getText())*Float.parseFloat(this.precio_adulto.getText());
        float P=Float.parseFloat(this.input_nino.getText())*Float.parseFloat(this.precio_nino.getText());
        float D=Float.parseFloat(this.input_infante.getText())*Float.parseFloat(this.precio_infante.getText());
        this.totalPrice.setText("$ "+Float.toString(A+P+D));
    }//GEN-LAST:event_panel_bookOpcionesMouseEntered

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        panel_bookOpciones.setVisible(false);
        panel_bookActivities.setVisible(true);
        this.jButton1.setVisible(true);
        this.jButton2.setVisible(true);
        tipo=0;
        ImageIcon img = new ImageIcon(getClass().getResource(""));
        ImageIcon ban = new ImageIcon(getClass().getResource(""));
        img_tour.setIcon(img);
        banner.setIcon(ban);
        name_tour.setText("");
        adult_price.setText("");//BD
        child_price.setText("");
        description.setText("");
        panel_Description.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_tarjetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tarjetaMouseEntered
        // TODO add your handling code here:
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Tarjeta_Select.png"));
        this.btn_tarjeta.setIcon(img);

    }//GEN-LAST:event_btn_tarjetaMouseEntered

    private void btn_tarjetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tarjetaMouseExited
        // TODO add your handling code here:
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Tarjeta.png"));
        this.btn_tarjeta.setIcon(img);
    }//GEN-LAST:event_btn_tarjetaMouseExited

    private void btn_facturacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_facturacionMouseEntered
        // TODO add your handling code here:
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Factura_Select.png"));
        this.btn_facturacion.setIcon(img);
    }//GEN-LAST:event_btn_facturacionMouseEntered

    private void btn_facturacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_facturacionMouseExited
        // TODO add your handling code here:
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Factura.png"));
        this.btn_facturacion.setIcon(img);
    }//GEN-LAST:event_btn_facturacionMouseExited

    private void btn_facturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_facturacionActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        String monedap="";
        if (date==null||time==null||this.input_adulto.getText()=="0"){
                        JOptionPane.showMessageDialog(null, "Debe seleccionar todos los campos", "SystemMessage: " + "Incomplete Form", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
        panel_bookOpciones.setVisible(false);
        panel_bookClient.setVisible(true);
        this.tour_Time.setText(time.substring(0,5)+ " Hrs");
        this.tour_date.setText(date);
        this.tour_name.setText(this.tourAr.get(tipo-1).nombre);
        if (this.btn_MX.isSelected())
            monedap = "MX";
        else {
            monedap  = "USD";
        }
        this.tour_total.setText(this.totalPrice.getText() + " "+ monedap);
        this.tour_adult.setText(this.input_adulto.getText());
        this.tour_child.setText(this.input_nino.getText());
        this.tour_infante.setText(this.input_infante.getText());
        }
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void btn_jungleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jungleMouseEntered
        // TODO add your handling code here: 
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Jungle01_Hover.jpg"));
        this.btn_jungle.setIcon(img);
    }//GEN-LAST:event_btn_jungleMouseEntered

    private void btn_jungleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jungleMouseExited
        // TODO add your handling code here: 
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Jungle01_Static.jpg"));
        this.btn_jungle.setIcon(img);
    }//GEN-LAST:event_btn_jungleMouseExited

    private void btn_mangroveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mangroveMouseEntered
        // TODO add your handling code here: 
        ImageIcon nepe =  new ImageIcon(getClass().getResource("/img/Mangroove_Hover.jpg")); 
        this.btn_mangrove.setIcon(nepe);
    }//GEN-LAST:event_btn_mangroveMouseEntered

    private void btn_mangroveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mangroveMouseExited
        // TODO add your handling code here:
        ImageIcon nepe =  new ImageIcon(getClass().getResource("/img/Mangroove_Static.jpg")); 
        this.btn_mangrove.setIcon(nepe);
    }//GEN-LAST:event_btn_mangroveMouseExited

    private void btn_scubaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_scubaMouseEntered
        // TODO add your handling code here: 
        ImageIcon nepe =  new ImageIcon(getClass().getResource("/img/Scuba_Hover.jpg")); 
        this.btn_scuba.setIcon(nepe);
    }//GEN-LAST:event_btn_scubaMouseEntered

    private void btn_scubaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_scubaMouseExited
        // TODO add your handling code here: 
        ImageIcon nepe =  new ImageIcon(getClass().getResource("/img/Scuba_Static.jpg")); 
        this.btn_scuba.setIcon(nepe);
    }//GEN-LAST:event_btn_scubaMouseExited

    private void btn_cancelar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelar1MouseEntered
        // TODO add your handling code here: 
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Btn_Cancelar_Hover.png"));
        this.btn_cancelar1.setIcon(img);
    }//GEN-LAST:event_btn_cancelar1MouseEntered

    private void btn_cancelar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelar1MouseExited
        // TODO add your handling code here: 
        ImageIcon nepe = new ImageIcon(getClass().getResource("/img/btn_Cancelar.jpg"));
        btn_cancelar1.setIcon(nepe);
    }//GEN-LAST:event_btn_cancelar1MouseExited

    private void btn_siguiente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siguiente1MouseEntered
        // TODO add your handling code here: 
        ImageIcon nepe = new ImageIcon(getClass().getResource("/img/Btn_Sig_Hover.png"));
        btn_siguiente1.setIcon(nepe);
    }//GEN-LAST:event_btn_siguiente1MouseEntered

    private void btn_siguiente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siguiente1MouseExited
        // TODO add your handling code here: 
        ImageIcon nepe = new ImageIcon(getClass().getResource("/img/btn_Siguiente.jpg"));
        btn_siguiente1.setIcon(nepe);
    }//GEN-LAST:event_btn_siguiente1MouseExited

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here
        panel_bookOpciones.setVisible(true);
        panel_bookClient.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagarActionPerformed
        // TODO add your handling code here:
       
        //SE CONFIRMA EL PAGO Y SE MUESTRA EL TOTAL
        int reply = JOptionPane.showConfirmDialog(null,"Confirmar pago. Total : "+ tour_total.getText(), "Confirmar Pago", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
        //Cliente
        //SE DEBE VERIFICAR SI NO HAY UN CLIENTE ACTIVO YA( SEGUIR COMPRANDO) O SI EL CLIENTE YA HABIA COMPRADO ANTES
        //SE DEBE ADQUIRIR EL ID DE FECHA TOUR Y ID CLIENTE 
        //SE DEBE GUARDAR EL RFC SI ESTA ACTIVADO, Y SE DEBE GUARDAR SI FUE EN DOLARES O MX Y SI FUE TARJETA O EFECTIVO
        if(conn.NewClient(input_email.getText(),input_nombre.getText(),input_apellido.getText(),input_numero.getText(),input_direccion.getText())&&conn.NewVendidos(2,2, Integer.parseInt(tour_adult.getText()),Integer.parseInt(tour_child.getText()),Integer.parseInt(tour_infante.getText()),precioTotal))
            JOptionPane.showMessageDialog(null, "Pago Exitoso", "SystemMessage: " + "Succesfull Payment", JOptionPane.INFORMATION_MESSAGE);
        //SE CREA VENDIDOS
        //DEBE AFECTAR A TURISTAS DE TABLA FECHATOUR
        else 
            JOptionPane.showMessageDialog(null,"Error al confirmar pago","Error",JOptionPane.INFORMATION_MESSAGE);
        
        }
        else {
            
        }
        
    }//GEN-LAST:event_btn_pagarActionPerformed

    private void btn_MXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MXActionPerformed
        if(this.btn_US.isSelected())
            this.btn_US.setSelected(false);
        
        this.precio_adulto.setText(Float.toString(this.tourAr.get(tipo).precioAdultoMX));
        this.precio_nino.setText(Float.toString(this.tourAr.get(tipo).precioNinoMX));
        this.precio_infante.setText(Float.toString(this.tourAr.get(tipo).precioInfanteMX));
        float A=Float.parseFloat(this.input_adulto.getText())*Float.parseFloat(this.precio_adulto.getText());
        float P=Float.parseFloat(this.input_nino.getText())*Float.parseFloat(this.precio_nino.getText());
        float D=Float.parseFloat(this.input_infante.getText())*Float.parseFloat(this.precio_infante.getText());
        this.totalPrice.setText("$ "+Float.toString(A+P+D));
        this.precioTotal=A+P+D;
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Ag_btn_mx.png"));
        moneda.setIcon(img);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MXActionPerformed

    private void btn_USActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_USActionPerformed
 if(this.btn_MX.isSelected())
            this.btn_MX.setSelected(false);
        this.precio_adulto.setText(Float.toString(this.tourAr.get(tipo).precioAdultoUS));
        this.precio_nino.setText(Float.toString(this.tourAr.get(tipo).precioNinoUS));
        this.precio_infante.setText(Float.toString(this.tourAr.get(tipo).precioInfanteUS));
        float A=Float.parseFloat(this.input_adulto.getText())*Float.parseFloat(this.precio_adulto.getText());
        float P=Float.parseFloat(this.input_nino.getText())*Float.parseFloat(this.precio_nino.getText());
        float D=Float.parseFloat(this.input_infante.getText())*Float.parseFloat(this.precio_infante.getText());
        this.totalPrice.setText("$ "+Float.toString(A+P+D));
        ImageIcon img = new ImageIcon(getClass().getResource("/img/Ag_btn_usd.png"));
        moneda.setIcon(img);        
    }//GEN-LAST:event_btn_USActionPerformed

    private void Horario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Horario3ActionPerformed
        // TODO add your handling code here:
        if (this.Horario3.isSelected()){
            this.Horario1.setSelected(false);
            this.Horario2.setSelected(false);
        }
        time=this.tourAr.get(tipo-1).hora3;
        getCalendarDate();
    }//GEN-LAST:event_Horario3ActionPerformed

    private void Horario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Horario2ActionPerformed
        // TODO add your handling code here:
        if (this.Horario2.isSelected()){
            this.Horario1.setSelected(false);
            this.Horario3.setSelected(false);
        }
        time=this.tourAr.get(tipo-1).hora2;
        getCalendarDate();
    }//GEN-LAST:event_Horario2ActionPerformed

    private void Horario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Horario1ActionPerformed
        // TODO add your handling code here:
        if (this.Horario1.isSelected()){
            this.Horario2.setSelected(false);
            this.Horario3.setSelected(false);
        }
        time=this.tourAr.get(tipo-1).hora1;
        getCalendarDate();
    }//GEN-LAST:event_Horario1ActionPerformed

    private void btn_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minActionPerformed
        // TODO add your handling code here:
         setExtendedState(JFrame.CROSSHAIR_CURSOR); 
    }//GEN-LAST:event_btn_minActionPerformed

    private void btn_efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_efectivoActionPerformed
        // TODO add your handling code here:
        //SE SELECCIONA EL PAGO EN EFECTIVO COMO PREDET 
        if (this.btn_efectivo.isSelected()){         
        ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Efectivo.png"));
        this.btn_efectivo.setIcon(img);
        this.efectivo_label.setVisible(false);
        }
        else {
            ImageIcon img =  new ImageIcon(getClass().getResource("/img/Dat_btn_Efectivo_Select.png"));
        this.btn_efectivo.setIcon(img);
        this.efectivo_label.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_efectivoActionPerformed

    private void btn_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Windows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Drager;
    private javax.swing.JToggleButton Extras_btn;
    private javax.swing.JPanel GeneralBG;
    private javax.swing.JToggleButton Horario1;
    private javax.swing.JToggleButton Horario2;
    private javax.swing.JToggleButton Horario3;
    private com.toedter.calendar.JCalendar Input_Date;
    private javax.swing.JLabel adult_price;
    private javax.swing.JLabel banner;
    private javax.swing.JLabel box;
    private javax.swing.JLabel box23;
    private javax.swing.JToggleButton btn_MX;
    private javax.swing.JToggleButton btn_US;
    private javax.swing.JButton btn_book;
    private javax.swing.JButton btn_cancelaciones;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelar1;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JLabel btn_codigoPromocion;
    private javax.swing.JToggleButton btn_efectivo;
    private javax.swing.JButton btn_facturacion;
    private javax.swing.JButton btn_jungle;
    private javax.swing.JButton btn_mangrove;
    private javax.swing.JButton btn_min;
    private javax.swing.JButton btn_pagar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_scuba;
    private javax.swing.JButton btn_seguirComprando;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JButton btn_siguiente1;
    private javax.swing.JButton btn_tarjeta;
    private javax.swing.JButton btn_terminos;
    private javax.swing.JPanel carrito;
    private javax.swing.JLabel child_price;
    private javax.swing.JLabel description;
    private javax.swing.JLabel efectivo_label;
    private javax.swing.JLabel fondito1;
    private javax.swing.JLabel fondito2;
    private javax.swing.JLabel fondito3;
    private javax.swing.JLabel fondito4;
    private javax.swing.JLabel fondito5;
    private javax.swing.JLabel fondito6;
    private javax.swing.JLabel fondito7;
    private javax.swing.JLabel fondo_pasos;
    private javax.swing.JLabel guy;
    private javax.swing.JLabel icon_guy;
    private javax.swing.JLabel img_tour;
    private javax.swing.JTextField input_adulto;
    private javax.swing.JTextField input_apellido;
    private javax.swing.JTextField input_direccion;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_infante;
    private javax.swing.JTextField input_nino;
    private javax.swing.JTextField input_nombre;
    private javax.swing.JTextField input_numero;
    private javax.swing.JTextField input_rfc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel moneda;
    private javax.swing.JLabel moneda1;
    private javax.swing.JLabel moneda2;
    private javax.swing.JLabel multic;
    private javax.swing.JLabel multic1;
    private javax.swing.JLabel multic2;
    private javax.swing.JLabel name_tour;
    private javax.swing.JPanel panel_Description;
    private javax.swing.JPanel panel_bookActivities;
    private javax.swing.JPanel panel_bookClient;
    private javax.swing.JPanel panel_bookOpciones;
    private javax.swing.JPanel panel_drag;
    private javax.swing.JPanel panel_opciones;
    private javax.swing.JPanel panel_pasos;
    private javax.swing.JLabel precio_adulto;
    private javax.swing.JLabel precio_infante;
    private javax.swing.JLabel precio_nino;
    private javax.swing.JSeparator separador_nombre;
    private javax.swing.JSeparator separador_nombre1;
    private javax.swing.JSeparator separador_nombre2;
    private javax.swing.JSeparator separador_nombre3;
    private javax.swing.JSeparator separador_nombre4;
    private javax.swing.JSeparator separador_nombre5;
    private javax.swing.JLabel title_adult;
    private javax.swing.JLabel title_adult1;
    private javax.swing.JLabel title_apellido;
    private javax.swing.JLabel title_carrito;
    private javax.swing.JLabel title_child;
    private javax.swing.JLabel title_child1;
    private javax.swing.JLabel title_date;
    private javax.swing.JLabel title_direccion;
    private javax.swing.JLabel title_email;
    private javax.swing.JLabel title_infate;
    private javax.swing.JLabel title_informacion;
    private javax.swing.JLabel title_nombre;
    private javax.swing.JLabel title_numero;
    private javax.swing.JLabel title_rfc;
    private javax.swing.JLabel title_time1;
    private javax.swing.JLabel title_tour;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JLabel tour_Time;
    private javax.swing.JLabel tour_adult;
    private javax.swing.JLabel tour_child;
    private javax.swing.JLabel tour_date;
    private javax.swing.JLabel tour_infante;
    private javax.swing.JLabel tour_name;
    private javax.swing.JLabel tour_total;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables

    private void getCalendarDate() {
        String[] arrayDate = Input_Date.getDate().toLocaleString().split("/");
        dateDB = arrayDate[2].substring(0, 4)+"-"+arrayDate[1]+"-"+arrayDate[0];
        date= arrayDate[0]+"/"+arrayDate[1]+"/"+arrayDate[2].substring(0, 4);
    }
}
